// <auto-generated />
using System;
using BaseApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProductsApp.Api.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20230107120451_secondMigration")]
    partial class secondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaseApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 1",
                            Price = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 2",
                            Price = 2
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 3",
                            Price = 3
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 4",
                            Price = 4
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 5",
                            Price = 5
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 6",
                            Price = 6
                        });
                });

            modelBuilder.Entity("BaseApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Person 1",
                            Role = "Unregistered Customer"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Person 2",
                            Role = "Registered Customer"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Person 3",
                            Role = "Staff"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Person 4",
                            Role = "Management"
                        });
                });

            modelBuilder.Entity("ProductsApp.Api.Models.Order", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            UserId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            UserId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
