// <auto-generated />
using System;
using BaseApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProductsApp.Api.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaseApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 1",
                            Price = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 2",
                            Price = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 3",
                            Price = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 4",
                            Price = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 5",
                            Price = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Example ",
                            InStock = true,
                            Name = "Example Product 6",
                            Price = 6
                        });
                });

            modelBuilder.Entity("BaseApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Person 1",
                            Role = "Unregistered Customer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Person 2",
                            Role = "Registered Customer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Person 3",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Person 4",
                            Role = "Management"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
